[project]
name = "fyp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "pydantic",
    "pydantic[email]",
    "python-jose[cryptography]",
    "python-multipart",
    "psycopg2-binary",
    "bcrypt",
    "transformers",
    "torch",
    "librosa",
    "soundfile",
    "accelerate",
    "protobuf>=6.33.2",
    "peft>=0.18.0",
]

[dependency-groups]
dev = [
    "pytest",
    "httpx",
]
