[project]
name = "fyp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "pydantic",
    "pydantic[email]",
    "python-jose[cryptography]",
    "python-multipart",
    "psycopg2-binary",
    "bcrypt",
    "transformers",
    "torch",
    "librosa",
    "soundfile",
    "accelerate",
    "protobuf>=6.33.2",
    "peft>=0.18.0",
    "httpx>=0.28.1",
    "mangum>=0.21.0",
    "slowapi>=0.1.9",
    "bleach>=6.0.0",
    "fastapi-mail>=1.6.2",
    "cryptography>=46.0.3",
    "python-dateutil==2.8.2",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-mock>=3.14.0",
    "httpx",
    "pytest-asyncio>=1.3.0",
]
