version = 0.1

[default.deploy.parameters]
stack_name = "voicescribe-backend"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "voicescribe-backend"
